import type { Metadata } from 'next';
import LeftSidebar from '@/app/components/LeftSidebar';
import SupabaseProvider from './supabase-provider';
import RightSection from '@/app/components/RightSection';
import './globals.css';

export const metadata: Metadata = {
  title: 'Tweeter clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="w-full h-full flex justify-center items-center relative bg-black text-white">
        <div className="w-full h-full flex relative justify-center">
          <LeftSidebar />
          <SupabaseProvider>{children}</SupabaseProvider>
          <RightSection />
        </div>
      </div>
      </body>
    </html>
  );
}
