import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Tweeter clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="w-full h-full flex justify-center items-center bg-black text-white"> */}
          {/* <div className="xl:max-w-[70vw] w-full h-full flex relative"> */}
            {/* <LeftSidebar /> */}
            {/* <SupabaseProvider> */}
              {children}
              {/* </SupabaseProvider> */}
            {/* <RightSection /> */}
          {/* </div> */}
        {/* </div> */}
      </body>
    </html>
  );
}
